/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import control.BookingControl;
import control.CustomerControl;
import domain.Booking;
import domain.Customer;
import domain.Ticket;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CJH
 */
public class PaymentPanel extends javax.swing.JPanel {

    /**
     * Creates new form PaymentPanel
     * @param psgList
     */
    private DefaultTableModel model;
    private BookingControl bControl;
    private CustomerControl cControl;
    
    public PaymentPanel(ArrayList<Ticket> psgList) {
        initComponents();
        model = (DefaultTableModel) table.getModel();
        bControl = new BookingControl();
        cControl = new CustomerControl();
        jrbMemberDisc.setEnabled(false);
        jrbMemberPoint.setEnabled(false);
        //jcbCC.setEnabled(false);
        jtfCC.setEnabled(false);
        //jcbCash.setEnabled(false);
        jtfCash.setEnabled(false);
        jbtSubmit2.setEnabled(false);
        jbtSubmit2.setEnabled(false);
        jbtPrintR.setEnabled(false);
        jbtPrintT.setEnabled(false);
        jlMemberID.setEnabled(false);
        jtfMemberID.setEnabled(false);
        jlPoint.setEnabled(false);
        jtfPoints.setEnabled(false);
        
        if(bControl.selectLatestRecord()==null) {
            jtfBookingID.setText("BK000001");
        } else {
            Booking booking = bControl.selectLatestRecord();
            jtfBookingID.setText(booking.getBookingID().substring(0, 2) + String.format("%06d", Integer.parseInt(booking.getBookingID().substring(2, 8))+1));
        }
        jtfScheduleID.setText(psgList.get(0).getSchedule().getScheduleID());
        double total = 0;
        for(int i=0; i<psgList.size(); i++) {
            model.addRow(new Object[] {psgList.get(i).getTicketID(), psgList.get(i).getPassengerName(), psgList.get(i).getPassengerContactNo(), psgList.get(i).getSeatNo(), String.format("%.2f", psgList.get(i).getSchedule().getRoute().getPrice().getPrice())});
            total += psgList.get(i).getSchedule().getRoute().getPrice().getPrice();
        }
        jtfTotalAmt.setText(String.format("%.2f", total));
        jtfGST.setText(String.format("%.2f", total*0.06));
        jtfNett.setText(jtfTotalAmt.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jlBookingID = new javax.swing.JLabel();
        jtfBookingID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jlScheduleID = new javax.swing.JLabel();
        jtfScheduleID = new javax.swing.JTextField();
        jlCustName = new javax.swing.JLabel();
        jtfCustName = new javax.swing.JTextField();
        jlCustContact = new javax.swing.JLabel();
        jtfCustContact = new javax.swing.JTextField();
        jlCustIC = new javax.swing.JLabel();
        jtfCustIC = new javax.swing.JTextField();
        jlError1 = new javax.swing.JLabel();
        jbtSubmit1 = new javax.swing.JButton();
        paymentDetailsPanel = new javax.swing.JPanel();
        jlTotalAmt = new javax.swing.JLabel();
        jtfTotalAmt = new javax.swing.JTextField();
        jlGST = new javax.swing.JLabel();
        jtfGST = new javax.swing.JTextField();
        jlDisc = new javax.swing.JLabel();
        jtfDisc = new javax.swing.JTextField();
        jlNett = new javax.swing.JLabel();
        jtfNett = new javax.swing.JTextField();
        jbtBack = new javax.swing.JButton();
        jrbMemberDisc = new javax.swing.JRadioButton();
        jrbMemberPoint = new javax.swing.JRadioButton();
        jtfCC = new javax.swing.JTextField();
        jtfCash = new javax.swing.JTextField();
        jlError2 = new javax.swing.JLabel();
        jbtPrintT = new javax.swing.JButton();
        jbtPrintR = new javax.swing.JButton();
        jlPaid = new javax.swing.JLabel();
        jtfPaid = new javax.swing.JTextField();
        jbtSubmit2 = new javax.swing.JButton();
        jlMemberID = new javax.swing.JLabel();
        jtfMemberID = new javax.swing.JTextField();
        jlPoint = new javax.swing.JLabel();
        jtfPoints = new javax.swing.JTextField();
        jlChanges = new javax.swing.JLabel();
        jtfChanges = new javax.swing.JTextField();
        jrbCC = new javax.swing.JRadioButton();
        jrbCash = new javax.swing.JRadioButton();
        jbtReturn = new javax.swing.JButton();
        jbtCancel = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Payment Panel");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jlBookingID.setText("Booking ID");

        jtfBookingID.setEditable(false);
        jtfBookingID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBookingIDActionPerformed(evt);
            }
        });

        table.setAutoCreateRowSorter(true);
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ticket No", "Name", "Contact No", "Seat No", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setPreferredWidth(50);
            table.getColumnModel().getColumn(3).setPreferredWidth(25);
        }

        jlScheduleID.setText("Schedule ID");

        jtfScheduleID.setEditable(false);
        jtfScheduleID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfScheduleIDActionPerformed(evt);
            }
        });

        jlCustName.setText("Customer Name");

        jlCustContact.setText("Customer Contact No");

        jlCustIC.setText("Customer IC No");

        jlError1.setText(" ");

        jbtSubmit1.setText("Submit");
        jbtSubmit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSubmit1ActionPerformed(evt);
            }
        });

        paymentDetailsPanel.setBackground(new java.awt.Color(153, 153, 153));
        paymentDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Payment Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        jlTotalAmt.setText("Total Amount (RM)");

        jtfTotalAmt.setEditable(false);

        jlGST.setText("GST (6%)");

        jtfGST.setEditable(false);

        jlDisc.setText("Discount");

        jtfDisc.setEditable(false);

        jlNett.setText("Nett Amount (RM)");

        jtfNett.setEditable(false);

        jbtBack.setText("Back");
        jbtBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBackActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbMemberDisc);
        jrbMemberDisc.setText("Membership Discount (10%)");
        jrbMemberDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMemberDiscActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbMemberPoint);
        jrbMemberPoint.setText("Use Points: ");
        jrbMemberPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMemberPointActionPerformed(evt);
            }
        });

        jlError2.setText(" ");

        jbtPrintT.setText("Print Tickets");
        jbtPrintT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPrintTActionPerformed(evt);
            }
        });

        jbtPrintR.setText("Print Receipt");
        jbtPrintR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPrintRActionPerformed(evt);
            }
        });

        jlPaid.setText("Paid Amount (RM))");

        jtfPaid.setEditable(false);

        jbtSubmit2.setText("Submit");

        jlMemberID.setText("Member ID");

        jtfMemberID.setEditable(false);

        jlPoint.setText("Points");

        jtfPoints.setEditable(false);

        jlChanges.setText("Changes (RM)");

        jtfChanges.setEditable(false);

        buttonGroup2.add(jrbCC);
        jrbCC.setText("Credit Card");

        buttonGroup2.add(jrbCash);
        jrbCash.setText("Cash");
        jrbCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCashActionPerformed(evt);
            }
        });

        jbtReturn.setText("Return to Ticketing");

        javax.swing.GroupLayout paymentDetailsPanelLayout = new javax.swing.GroupLayout(paymentDetailsPanel);
        paymentDetailsPanel.setLayout(paymentDetailsPanelLayout);
        paymentDetailsPanelLayout.setHorizontalGroup(
            paymentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentDetailsPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(paymentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paymentDetailsPanelLayout.createSequentialGroup()
                        .addComponent(jlChanges)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtPrintR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtPrintT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtReturn)
                        .addGap(18, 18, 18))
                    .addGroup(paymentDetailsPanelLayout.createSequentialGroup()
                        .addGroup(paymentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(paymentDetailsPanelLayout.createSequentialGroup()
                                .addGroup(paymentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlTotalAmt)
                                    .addComponent(jlGST)
                                    .addComponent(jlDisc)
                                    .addComponent(jlNett))
                                .addGap(18, 18, 18)
                                .addGroup(paymentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfTotalAmt)
                                    .addComponent(jtfGST)
                                    .addComponent(jtfDisc)
                                    .addComponent(jtfNett, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                            .addGroup(paymentDetailsPanelLayout.createSequentialGroup()
                                .addComponent(jlPaid)
                                .addGap(18, 18, 18)
                                .addGroup(paymentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfPaid)
                                    .addComponent(jtfChanges))))
                        .addGap(18, 18, 18)
                        .addGroup(paymentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paymentDetailsPanelLayout.createSequentialGroup()
                                .addGroup(paymentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jrbCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jrbCash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(paymentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(paymentDetailsPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jtfCash, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentDetailsPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jtfCC, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(14, 14, 14)
                                .addComponent(jbtSubmit2))
                            .addComponent(jlError2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(paymentDetailsPanelLayout.createSequentialGroup()
                                .addGroup(paymentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jrbMemberDisc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(paymentDetailsPanelLayout.createSequentialGroup()
                                        .addComponent(jlMemberID)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12)
                                .addGroup(paymentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(paymentDetailsPanelLayout.createSequentialGroup()
                                        .addComponent(jlPoint)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfPoints))
                                    .addComponent(jrbMemberPoint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        paymentDetailsPanelLayout.setVerticalGroup(
            paymentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paymentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTotalAmt)
                    .addComponent(jtfTotalAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlMemberID)
                    .addComponent(jtfMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPoint)
                    .addComponent(jtfPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(paymentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paymentDetailsPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paymentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlGST)
                            .addComponent(jtfGST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbMemberDisc)
                            .addComponent(jrbMemberPoint))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paymentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlDisc)
                            .addComponent(jtfDisc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbCC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paymentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNett)
                            .addComponent(jtfNett, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbCash)))
                    .addGroup(paymentDetailsPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jbtSubmit2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paymentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPaid)
                    .addComponent(jtfPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlError2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paymentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlChanges)
                    .addComponent(jtfChanges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtPrintR)
                    .addComponent(jbtPrintT)
                    .addComponent(jbtBack)
                    .addComponent(jbtReturn))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jbtCancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlScheduleID)
                                .addGap(18, 18, 18)
                                .addComponent(jtfScheduleID, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlBookingID)
                                .addGap(24, 24, 24)
                                .addComponent(jtfBookingID, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlError1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jlCustName, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                            .addComponent(jtfCustName, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jlCustIC, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jtfCustIC, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jlCustContact)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jtfCustContact, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addComponent(jbtSubmit1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jbtCancel))))
                        .addGap(0, 136, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(paymentDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfBookingID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlBookingID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlScheduleID)
                    .addComponent(jtfScheduleID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCustName)
                    .addComponent(jtfCustName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCustContact)
                    .addComponent(jtfCustContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCustIC)
                    .addComponent(jtfCustIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtCancel)
                    .addComponent(jbtSubmit1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlError1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paymentDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfBookingIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBookingIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfBookingIDActionPerformed

    private void jtfScheduleIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfScheduleIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfScheduleIDActionPerformed

    private void jbtBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtBackActionPerformed

    private void jbtSubmit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSubmit1ActionPerformed
        // TODO add your handling code here:
        String custName = jtfCustName.getText();
        String custContact = jtfCustContact.getText();
        String custICNo = jtfCustIC.getText();
        if(custName.equals("")||custContact.equals("")||custICNo.equals("")) {
            jlError1.setText("Please fill in all the required information.");
            jlError1.setForeground(Color.red);
        } else if(custName.length()>30) {
            jlError1.setText("Name not more than 30 words.");
            jlError1.setForeground(Color.red);
        } else if(!custContact.matches("[\\d]{3}-[\\d]{7,8}")) {
            jlError1.setText("Invalid contact number format.");
            jlError1.setForeground(Color.red);
        } else if(!custICNo.matches("[\\d]{6}-[\\d]{2}-[\\d]{4}")) {
            jlError1.setText("Invalid IC number format.");
            jlError1.setForeground(Color.red);
        } else {
            jlError1.setText(" ");
            Customer customer = cControl.selectRecordByNameContactICNo(custName, custContact, custICNo);
            if(customer!=null) {
                if(customer.getStatus()==' ') {
                    jtfDisc.setText("0");                  
                } else {
                    jrbMemberDisc.setSelected(true);
                    //jtfDisc.setText(String.format("%.2f",));
                }
            }
        }
    }//GEN-LAST:event_jbtSubmit1ActionPerformed

    private void jrbCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbCashActionPerformed

    private void jrbMemberPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMemberPointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbMemberPointActionPerformed

    private void jrbMemberDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMemberDiscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbMemberDiscActionPerformed

    private void jbtPrintTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPrintTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtPrintTActionPerformed

    private void jbtPrintRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPrintRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtPrintRActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtBack;
    private javax.swing.JButton jbtCancel;
    private javax.swing.JButton jbtPrintR;
    private javax.swing.JButton jbtPrintT;
    private javax.swing.JButton jbtReturn;
    private javax.swing.JButton jbtSubmit1;
    private javax.swing.JButton jbtSubmit2;
    private javax.swing.JLabel jlBookingID;
    private javax.swing.JLabel jlChanges;
    private javax.swing.JLabel jlCustContact;
    private javax.swing.JLabel jlCustIC;
    private javax.swing.JLabel jlCustName;
    private javax.swing.JLabel jlDisc;
    private javax.swing.JLabel jlError1;
    private javax.swing.JLabel jlError2;
    private javax.swing.JLabel jlGST;
    private javax.swing.JLabel jlMemberID;
    private javax.swing.JLabel jlNett;
    private javax.swing.JLabel jlPaid;
    private javax.swing.JLabel jlPoint;
    private javax.swing.JLabel jlScheduleID;
    private javax.swing.JLabel jlTotalAmt;
    private javax.swing.JRadioButton jrbCC;
    private javax.swing.JRadioButton jrbCash;
    private javax.swing.JRadioButton jrbMemberDisc;
    private javax.swing.JRadioButton jrbMemberPoint;
    private javax.swing.JTextField jtfBookingID;
    private javax.swing.JTextField jtfCC;
    private javax.swing.JTextField jtfCash;
    private javax.swing.JTextField jtfChanges;
    private javax.swing.JTextField jtfCustContact;
    private javax.swing.JTextField jtfCustIC;
    private javax.swing.JTextField jtfCustName;
    private javax.swing.JTextField jtfDisc;
    private javax.swing.JTextField jtfGST;
    private javax.swing.JTextField jtfMemberID;
    private javax.swing.JTextField jtfNett;
    private javax.swing.JTextField jtfPaid;
    private javax.swing.JTextField jtfPoints;
    private javax.swing.JTextField jtfScheduleID;
    private javax.swing.JTextField jtfTotalAmt;
    private javax.swing.JPanel paymentDetailsPanel;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
