/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import control.RouteControl;
import control.ScheduleControl;
import domain.Route;
import domain.Schedule;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author CJH
 */
public class Ticketing extends javax.swing.JPanel {

    /**
     * Creates new form Ticketing
     */
    private RouteControl rControl;
    private ScheduleControl sControl;
    private BusA busA;
    
    public Ticketing() {
        initComponents();
        rControl = new RouteControl();
        sControl = new ScheduleControl();
        busA = new BusA();
       
        ArrayList<Route> routeList = rControl.selectAllRecord();  
        int length = routeList.size();
        String[] routeChoice = new String[length];
        for(int i=0; i<length; i++) {
            routeChoice[i] = routeList.get(i).getDestination();
        }
        DefaultComboBoxModel model = new DefaultComboBoxModel(routeChoice);
        jcbTo.setModel(model);
        
        jtfFrom.setText("CJH Terminal");   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel0 = new javax.swing.JPanel();
        firstStep = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcbTo = new javax.swing.JComboBox();
        jtfFrom = new javax.swing.JTextField();
        jdcDate = new com.toedter.calendar.JDateChooser();
        jbtCheck = new javax.swing.JButton();
        jtfErrorMsg = new javax.swing.JLabel();
        jbtReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlSchedule = new javax.swing.JList();
        jbtBack = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(740, 640));
        setMinimumSize(new java.awt.Dimension(740, 640));
        setPreferredSize(new java.awt.Dimension(740, 640));

        panel0.setMaximumSize(new java.awt.Dimension(740, 640));
        panel0.setMinimumSize(new java.awt.Dimension(740, 640));
        panel0.setPreferredSize(new java.awt.Dimension(740, 640));

        firstStep.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ticketing Information");

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel2.setText("From");

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel3.setText("To");

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel4.setText("Date");

        jtfFrom.setEditable(false);

        jdcDate.setDateFormatString("yyyy-MM-dd");

        jbtCheck.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jbtCheck.setText("Check");
        jbtCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCheckActionPerformed(evt);
            }
        });

        jtfErrorMsg.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jtfErrorMsg.setText(" ");

        jbtReset.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jbtReset.setText("Reset");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtCheck)
                        .addGap(18, 18, 18)
                        .addComponent(jbtReset)
                        .addGap(47, 47, 47))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel2)
                                        .addGap(68, 68, 68))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfFrom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbTo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jdcDate, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(66, 66, 66))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jtfErrorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jdcDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtCheck)
                    .addComponent(jbtReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfErrorMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jlSchedule.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jlSchedule.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jlSchedule.setToolTipText("");
        jlSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlScheduleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jlSchedule);

        jbtBack.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jbtBack.setText("Back");

        javax.swing.GroupLayout firstStepLayout = new javax.swing.GroupLayout(firstStep);
        firstStep.setLayout(firstStepLayout);
        firstStepLayout.setHorizontalGroup(
            firstStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstStepLayout.createSequentialGroup()
                .addContainerGap(222, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(215, 215, 215))
            .addGroup(firstStepLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(firstStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(firstStepLayout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(jbtBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        firstStepLayout.setVerticalGroup(
            firstStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstStepLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtBack)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout panel0Layout = new javax.swing.GroupLayout(panel0);
        panel0.setLayout(panel0Layout);
        panel0Layout.setHorizontalGroup(
            panel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel0Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(firstStep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel0Layout.setVerticalGroup(
            panel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel0Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(firstStep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        firstStep.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jlScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlScheduleMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 1) {
            //seatPanel.add(new JLabel(""));
            String selectedSchedule = jlSchedule.getSelectedValue().toString();
            if(selectedSchedule.endsWith("Type A")) {
                panel0.remove(panel0.getComponent(0));
                panel0.revalidate();
                panel0.repaint();
                panel0.add(busA, BorderLayout.CENTER);
                panel0.revalidate();
                panel0.repaint();
                busA.setPreferredSize(new Dimension(740, 640));
                busA.setVisible(true);
                panel0.setPreferredSize(new Dimension(740, 640));
            } else if(selectedSchedule.endsWith("Type B")) {
                panel0.remove(panel0.getComponent(0));
                panel0.revalidate();
                panel0.repaint();
                panel0.add(new BusB(), BorderLayout.CENTER);
            } else if(selectedSchedule.endsWith("Double Decker")) {
                panel0.remove(panel0.getComponent(0));
                panel0.revalidate();
                panel0.repaint();
                panel0.add(new BusDD(), BorderLayout.CENTER);
            }
        }
    }//GEN-LAST:event_jlScheduleMouseClicked

    private void jbtCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCheckActionPerformed
        // TODO add your handling code here:
        DefaultListModel scheduleList = new DefaultListModel();
        jlSchedule.setModel(scheduleList);

        if(((JTextField)jdcDate.getDateEditor().getUiComponent()).getText().isEmpty()) {
            jtfErrorMsg.setText("Please select a date.");
            jtfErrorMsg.setForeground(Color.red);
        } else if(!((JTextField)jdcDate.getDateEditor().getUiComponent()).getText().matches("^(19|20)\\d\\d-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$")) {
            jtfErrorMsg.setText("Please select a valid date.");
            jtfErrorMsg.setForeground(Color.red);
        } else {
            jtfErrorMsg.setText("");
            Route routeSelected = rControl.selectRecordByDestination(jcbTo.getSelectedItem().toString());
            String dateSelected = ((JTextField)jdcDate.getDateEditor().getUiComponent()).getText();
            ArrayList<Schedule> scheduleDisplayList = sControl.selectRecordByRouteAndDate(routeSelected, dateSelected);
            for(int i=0; i<scheduleDisplayList.size(); i++) {
                scheduleList.addElement((i+1) + ".) Time(24HR) : " + scheduleDisplayList.get(i).getDepartureTime().substring(0, 5) + " - Bus Type : " + scheduleDisplayList.get(i).getBus().getBusType().getBusType());
            }
        }
    }//GEN-LAST:event_jbtCheckActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel firstStep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtBack;
    private javax.swing.JButton jbtCheck;
    private javax.swing.JButton jbtReset;
    private javax.swing.JComboBox jcbTo;
    private com.toedter.calendar.JDateChooser jdcDate;
    private javax.swing.JList jlSchedule;
    private javax.swing.JLabel jtfErrorMsg;
    private javax.swing.JTextField jtfFrom;
    private javax.swing.JPanel panel0;
    // End of variables declaration//GEN-END:variables
}
